### PR TITLE
Removed connect (shouldn't be needed), added fallback method, tests

### PR DESCRIPTION
**Pull request by dz0ny**
and also fixes #6

### CODE REVIEW

**Comment by sindresorhus** [comment]
Please explain your PR.

**Comment by dz0ny** [comment]
For starters grunt connect is not needed by livereload, aka tiny-lr already has the server for js snippet. That part confused some users. Livereload task was unnecessary dependent on tinyl-lr(reload part) and regarde(changed-files). I've added fallback method that uses http get request (supported by tiny-lr). The #6 is fixed by this fallback method. You can now do grunt livereload and it will just reload page(if livereload server is running :) ).

**Comment by sindresorhus** [comment]
// @sleeper

**Comment by dylang** [comment]
I would **strongly** prefer if `spawn:true` then don't worry that you don't know _what_ was changed and just reload the page.

Without `spawn:true` a bad `jshint` or failed unit test will kill grunt instead of waiting for the file to be corrected.

**Comment by sleeper** [comment]
Agreed on the dependencies on `regarde` and `tiny-lr` in `livereload` task.
However, the connect part is needed to insert on the fly the livereload snippet in the looked-at page ... This part is not, AFAIK, included in tiny-lr, and we do not want to clutter the production files with this snippet.

**Comment by dz0ny** [comment]
@sleeper Three solutions: 
1. Environments (production, development), you don't include js snippet if process.enviroment is set as production. (works everywhere)
2. Use browser extensions or bookmark-let (works only for js,css files)
3. Implement task that servers current directory and lr-snippet

Connect part is in essence self serving server, which injects livereload to pages. This is usefully only in case you are developing single-pages apps, but then, again you have custom server somewhere.

**Comment by sebv** [comment]
Could also add proxy functionality to do the job like in grunt-reload. Let you have a clean dev config always testable.

something like this

```
livereload-start: {
        proxy: {
            port: 3000,
            target: {
               host: localhost
               port: 3001
            }
        }
    },
```

**Comment by Arkkimaagi** [comment]
I have the snippet just where I want it in the code and I'm running my code on pow server, not on the connect.

Basicly the connect server just sits there idle and I feel that it's silly.

Could this possibly be an option to turn on or off?

**Comment by Iristyle** [comment]
I would suggest not totally removing `connect` from the docs, but rather moving it to an advanced section of the docs.

While it might not be needed, AFAICT it's needed to use any middleware.  

For instance, we're using [requirejs-glob](https://github.com/OpenWebStack/requirejs-glob) middleware in an AngularJS app.  The only way for us to be able to load our services / controllers / directives / etc (without running everything through r.js) is is to have this middleware available to handle urls meeting a certain regex match.

If you completely remove `connect` from the docs, I would have had no idea that that was even possible.

**Comment by rschmukler** [comment]
+1 connect shouldn't be required. Some of us prefer the extension

**Comment by sindresorhus** [comment]
[grunt-contrib-watch](https://github.com/gruntjs/grunt-contrib-watch) now have Livereload built-in. We came to the conclusion that it was the best solution. We're deprecating this task very soon.

It no longer requires or recommends the use of Connect. But you can still use the [connect-livereload](https://github.com/intesso/connect-livereload) middleware if wanted.

**Pull request closed without merging**
