### PR TITLE
Fixes #25: 40kb limit on html files

### PR DESCRIPTION
**Pull request by getfatday**
The `livereloadSnippet` sets the `Content-Length` of a response on each call to `res.write`. Additional calls will overwrite the content length without considering previous calls. Also, data passed to `res.end` are not taken into consideration.

This modification overrides the default response `write`, `writeHeader`, and `end` methods and writes the concatenated contents of all `write` requests in the new `end` method.

I tried to find a less hostile way of accomplishing this without overriding the response methods, but couldn't find any. Suggestions welcome.

### CODE REVIEW

**Comment by sindresorhus** [comment]
@getfatday what are your thoughts on #26?

## 

// @sleeper

**Comment by getfatday** [comment]
@sindresorhus this pull request now resolves #25 and #26

**Comment by pajtai** [comment]
~~I still get a truncated response on a 65kb index.html file.~~

edit: nevermind - confirm fix - thought I was pulling from the right branch, but I was not.

**Comment by mlegenhausen** [comment]
Same problem here on a 42kb index.html file.

**Comment by pajtai** [comment]
@mlegenhausen - Make sure you're pulling from the branch that has 5508456 - looks like it's multi-write (not fix-content-length)

**Comment by mlegenhausen** [comment]
Thanks for the tipp I pulled from master.

**Comment by nagey** [comment]
after installing with `npm install https://github.com/getfatday/grunt-contrib-livereload/tarball/fix-content-length` I still get the truncation at 40kb…

**Comment by pajtai** [comment]
@nagey - It looks like the Fixes #25: 40kb limit on html files is actually in the `multi-write` branch, so the following worked for me:

 `npm install https://github.com/getfatday/grunt-contrib-livereload/tarball/multi-write`

(I thought it was the fix-content-length branch intially too)

**Comment by vladikoff** [comment]
Issue fixed after I removed `node-modules/grunt-contrib-livereload` and ran `npm install https://github.com/getfatday/grunt-contrib-livereload/tarball/multi-write` on OS X 10.8 with a 104 kb file.

Could someone please merge the changes into the actual repo?

**Comment by sleeper** [comment]
@getfatday Would you please squash the commit ?

**Comment by sindresorhus** [comment]
Tests fail after the last commit fe775b14efffd835ced7b305c1595aa4b28be018

**Comment by getfatday** [comment]
Squashing, rebasing and verifying it now. Will post when tests pass.

**Comment by mlegenhausen** [comment]
Can confirm squashed multi-write version is working :)

**Comment by getfatday** [comment]
Build fails on node 0.10.x due to yaymukund/grunt-simple-mocha#28 not being published to npm yet. Pulling the HEAD of that repo and linking npm locally will successfully build

**Comment by sleeper** [comment]
@sindresorhus Seems like I'm no more maintainer for this one ... so I cannot merge :(
Could you help here ?

**Comment by sindresorhus** [comment]
@getfatday can you fix the merge conflict?

@sleeper yup, was going to, but was waiting for the tests to pass.

**Comment by sleeper** [comment]
k
Could you re-add me to the commiter list ?

**Comment by getfatday** [comment]
@sindresorhus conflict resolved.

**Comment by sindresorhus** [comment]
@getfatday thanks for the fix. Feels good having the resolved.

**Comment by sindresorhus** [comment]
@sleeper I would, but I don't have the rights to do it.

**Comment by getfatday** [comment]
@sindresorhus no problem, thanks for the help.

**Comment by digitaljhelms** [comment]
Is there an ETA on when this package will be updated to 0.1.3 on the npm registry to include this PR?

_I also left a comment on #25 a week ago but haven't seen a response; I'm anticipating a "when all open PR have been closed" response, but I think that's a bit open ended considering this PR was solved 2 months ago. #fingerscrossed_

**Comment by sindresorhus** [comment]
@digitaljhelms try out grunt-contrib-watch combined with connect-livereload instead. See the readme.

For usage example, see: https://github.com/yeoman/generator-webapp/blob/master/app/templates/Gruntfile.js#L43-L54

**Comment by digitaljhelms** [comment]
Thanks for the reply @sindresorhus 

I have created a branch in our project to do just what you're suggesting (and for future yeoman/grunt projects I will be sure not to use this package again considering its apparently being phased out) however I've run into a few issues swapping out the packages and refactoring the grunt tasks, so it just seems easier to me to update the grunt-contrib-livereload package in our project (that 18 developers are currently working in) to 0.1.3 and keep everything else we know to be working properly in place, considering the only issue we're having is this 40kb limit and the patch has already been accepted...

**Comment by sindresorhus** [comment]
@digitaljhelms yeah, I get that. You can easily use it directly without a new release though: `"grunt-contrib-livereload": "gruntjs/grunt-contrib-livereload"` to get master, which won't be updated anymore.

**Pull request merged**
